[package]
name = "p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
rfd = { version = "0.15.2" }

get_if_addrs = "0.5"
local-ip-address = "0.5"
bytes = "1.10.1"
